import numpy as np
from scipy import stats
from scipy.stats import norm
from scipy.stats import expon
from scipy.stats import uniform
from scipy.stats import gamma
from scipy.stats import hypergeom
from scipy import stats
from scipy.integrate import quad
import seaborn as sns
from functools import partial
from scipy.integrate import quad
import scipy.integrate as integrate
import scipy.special as special
from scipy.stats import expon
from scipy.stats import t
import matplotlib.pyplot as plt
import pandas as pd
